import { NodeType } from "@/generated/prisma";

export interface NodeMetadata {
  type: NodeType;
  label: string;
  description: string;
  category:
    | "trigger"
    | "execution"
    | "logic"
    | "data"
    | "utility"
    | "integration"
    | "ai";
  color: string;
  inputs: number;
  outputs: number;
  icon: string;
  credentialType?: string;
  docs?: string;
}

export const nodeMetadataMap: Record<string, NodeMetadata> = {
  [NodeType.INITIAL]: {
    type: NodeType.INITIAL,
    label: "Initial",
    description: "Starting point of the workflow",
    category: "utility",
    color: "#6b7280",
    inputs: 0,
    outputs: 0,
    icon: "Circle",
  },
  [NodeType.MANUAL_TRIGGER]: {
    type: NodeType.MANUAL_TRIGGER,
    label: "Manual Trigger",
    description: "Manually trigger workflow execution",
    category: "trigger",
    color: "#22c55e",
    inputs: 0,
    outputs: 1,
    icon: "Play",
  },
  [NodeType.WEBHOOK_TRIGGER]: {
    type: NodeType.WEBHOOK_TRIGGER,
    label: "Webhook Trigger",
    description: "Trigger workflow via HTTP webhook",
    category: "trigger",
    color: "#22c55e",
    inputs: 0,
    outputs: 1,
    icon: "Webhook",
  },
  [NodeType.SCHEDULE_TRIGGER]: {
    type: NodeType.SCHEDULE_TRIGGER,
    label: "Schedule Trigger",
    description: "Trigger workflow on a cron schedule",
    category: "trigger",
    color: "#22c55e",
    inputs: 0,
    outputs: 1,
    icon: "Clock",
  },
  [NodeType.CHAT_TRIGGER]: {
    type: NodeType.CHAT_TRIGGER,
    label: "Chat Trigger",
    description: "Trigger workflow from chat message",
    category: "trigger",
    color: "#22c55e",
    inputs: 0,
    outputs: 1,
    icon: "MessageCircle",
  },
  [NodeType.GOOGLE_FORM_TRIGGER]: {
    type: NodeType.GOOGLE_FORM_TRIGGER,
    label: "Google Form Trigger",
    description: "Trigger when Google Form is submitted",
    category: "trigger",
    color: "#22c55e",
    inputs: 0,
    outputs: 1,
    icon: "FileText",
  },
  [NodeType.STRIPE_TRIGGER]: {
    type: NodeType.STRIPE_TRIGGER,
    label: "Stripe Trigger",
    description: "Trigger on Stripe webhook events",
    category: "trigger",
    color: "#22c55e",
    inputs: 0,
    outputs: 1,
    icon: "CreditCard",
  },
  [NodeType.EMAIL_TRIGGER]: {
    type: NodeType.EMAIL_TRIGGER,
    label: "Email Trigger",
    description: "Trigger workflow when new IMAP email arrives",
    category: "trigger",
    color: "#22c55e",
    inputs: 0,
    outputs: 1,
    icon: "Mail",
    credentialType: "IMAP",
  },
  [NodeType.ERROR_TRIGGER]: {
    type: NodeType.ERROR_TRIGGER,
    label: "Error Trigger",
    description: "Trigger workflow when another workflow fails",
    category: "trigger",
    color: "#22c55e",
    inputs: 0,
    outputs: 1,
    icon: "Bug",
  },
  [NodeType.HTTP_REQUEST]: {
    type: NodeType.HTTP_REQUEST,
    label: "HTTP Request",
    description: "Make HTTP/REST API requests",
    category: "execution",
    color: "#3b82f6",
    inputs: 1,
    outputs: 1,
    icon: "Globe",
  },
  [NodeType.OPENAI]: {
    type: NodeType.OPENAI,
    label: "OpenAI",
    description: "Generate text using OpenAI GPT models",
    category: "ai",
    color: "#8b5cf6",
    inputs: 1,
    outputs: 1,
    icon: "Brain",
    credentialType: "OPENAI",
  },
  [NodeType.ANTHROPIC]: {
    type: NodeType.ANTHROPIC,
    label: "Anthropic",
    description: "Generate text using Claude models",
    category: "ai",
    color: "#8b5cf6",
    inputs: 1,
    outputs: 1,
    icon: "Brain",
    credentialType: "ANTHROPIC",
  },
  [NodeType.GEMINI]: {
    type: NodeType.GEMINI,
    label: "Google Gemini",
    description: "Generate text using Gemini models",
    category: "ai",
    color: "#8b5cf6",
    inputs: 1,
    outputs: 1,
    icon: "Brain",
    credentialType: "GEMINI",
  },
  [NodeType.IF_CONDITION]: {
    type: NodeType.IF_CONDITION,
    label: "IF Condition",
    description: "Branch workflow based on conditions",
    category: "logic",
    color: "#f59e0b",
    inputs: 1,
    outputs: 2,
    icon: "GitBranch",
  },
  [NodeType.SWITCH]: {
    type: NodeType.SWITCH,
    label: "Switch",
    description: "Route to multiple branches",
    category: "logic",
    color: "#f59e0b",
    inputs: 1,
    outputs: 4,
    icon: "GitFork",
  },
  [NodeType.CODE]: {
    type: NodeType.CODE,
    label: "Code",
    description: "Execute custom JavaScript code",
    category: "data",
    color: "#ec4899",
    inputs: 1,
    outputs: 1,
    icon: "Code",
  },
  [NodeType.TRANSFORM]: {
    type: NodeType.TRANSFORM,
    label: "Transform",
    description: "Transform and reshape data",
    category: "data",
    color: "#ec4899",
    inputs: 1,
    outputs: 1,
    icon: "Shuffle",
  },
  [NodeType.DISCORD]: {
    type: NodeType.DISCORD,
    label: "Discord",
    description: "Send messages to Discord",
    category: "integration",
    color: "#6366f1",
    inputs: 1,
    outputs: 1,
    icon: "MessageSquare",
  },
  [NodeType.SLACK]: {
    type: NodeType.SLACK,
    label: "Slack",
    description: "Send messages to Slack",
    category: "integration",
    color: "#6366f1",
    inputs: 1,
    outputs: 1,
    icon: "Hash",
  },
  [NodeType.TELEGRAM]: {
    type: NodeType.TELEGRAM,
    label: "Telegram",
    description: "Send messages via Telegram Bot",
    category: "integration",
    color: "#6366f1",
    inputs: 1,
    outputs: 1,
    icon: "Send",
    credentialType: "TELEGRAM",
  },
  [NodeType.EMAIL_SMTP]: {
    type: NodeType.EMAIL_SMTP,
    label: "Email (SMTP)",
    description: "Send emails via SMTP",
    category: "integration",
    color: "#6366f1",
    inputs: 1,
    outputs: 1,
    icon: "Mail",
    credentialType: "SMTP",
  },
  [NodeType.GITHUB]: {
    type: NodeType.GITHUB,
    label: "GitHub",
    description: "Interact with GitHub API",
    category: "integration",
    color: "#6366f1",
    inputs: 1,
    outputs: 1,
    icon: "Github",
    credentialType: "GITHUB_TOKEN",
  },
  [NodeType.NOTION]: {
    type: NodeType.NOTION,
    label: "Notion",
    description: "Read/write Notion databases",
    category: "integration",
    color: "#6366f1",
    inputs: 1,
    outputs: 1,
    icon: "BookOpen",
    credentialType: "NOTION",
  },
  [NodeType.STICKY_NOTE]: {
    type: NodeType.STICKY_NOTE,
    label: "Sticky Note",
    description: "Add comments to the workflow",
    category: "utility",
    color: "#fbbf24",
    inputs: 0,
    outputs: 0,
    icon: "StickyNote",
  },
  [NodeType.FILTER]: {
    type: NodeType.FILTER,
    label: "Filter",
    description: "Filter data based on conditions",
    category: "logic",
    color: "#f59e0b",
    inputs: 1,
    outputs: 1,
    icon: "Filter",
  },
  [NodeType.LOOP]: {
    type: NodeType.LOOP,
    label: "Loop",
    description: "Iterate over data items",
    category: "logic",
    color: "#f59e0b",
    inputs: 1,
    outputs: 1,
    icon: "Repeat",
  },
  [NodeType.MERGE]: {
    type: NodeType.MERGE,
    label: "Merge",
    description: "Merge multiple data streams",
    category: "logic",
    color: "#f59e0b",
    inputs: 2,
    outputs: 1,
    icon: "Merge",
  },
  [NodeType.SPLIT]: {
    type: NodeType.SPLIT,
    label: "Split",
    description: "Split data into multiple streams",
    category: "logic",
    color: "#f59e0b",
    inputs: 1,
    outputs: 2,
    icon: "Split",
  },
  [NodeType.WAIT_DELAY]: {
    type: NodeType.WAIT_DELAY,
    label: "Wait/Delay",
    description: "Pause execution for a duration",
    category: "logic",
    color: "#f59e0b",
    inputs: 1,
    outputs: 1,
    icon: "Timer",
  },
  [NodeType.STOP_ERROR]: {
    type: NodeType.STOP_ERROR,
    label: "Stop & Error",
    description: "Stop execution with error",
    category: "logic",
    color: "#ef4444",
    inputs: 1,
    outputs: 0,
    icon: "XCircle",
  },
  [NodeType.SUB_WORKFLOW]: {
    type: NodeType.SUB_WORKFLOW,
    label: "Sub-Workflow",
    description: "Execute another workflow",
    category: "logic",
    color: "#f59e0b",
    inputs: 1,
    outputs: 1,
    icon: "Workflow",
  },
  [NodeType.AGGREGATE]: {
    type: NodeType.AGGREGATE,
    label: "Aggregate",
    description: "Aggregate data values",
    category: "data",
    color: "#ec4899",
    inputs: 1,
    outputs: 1,
    icon: "BarChart",
  },
  [NodeType.SORT]: {
    type: NodeType.SORT,
    label: "Sort",
    description: "Sort data by field",
    category: "data",
    color: "#ec4899",
    inputs: 1,
    outputs: 1,
    icon: "ArrowUpDown",
  },
  [NodeType.REMOVE_DUPLICATES]: {
    type: NodeType.REMOVE_DUPLICATES,
    label: "Remove Duplicates",
    description: "Remove duplicate items",
    category: "data",
    color: "#ec4899",
    inputs: 1,
    outputs: 1,
    icon: "Copy",
  },
  [NodeType.DATE_TIME]: {
    type: NodeType.DATE_TIME,
    label: "Date/Time",
    description: "Parse and format dates",
    category: "data",
    color: "#ec4899",
    inputs: 1,
    outputs: 1,
    icon: "Calendar",
  },
  [NodeType.CRYPTO]: {
    type: NodeType.CRYPTO,
    label: "Crypto",
    description: "Hash, encrypt, decode data",
    category: "data",
    color: "#ec4899",
    inputs: 1,
    outputs: 1,
    icon: "Key",
  },
  [NodeType.MARKDOWN_HTML]: {
    type: NodeType.MARKDOWN_HTML,
    label: "Markdown/HTML",
    description: "Convert between Markdown and HTML",
    category: "data",
    color: "#ec4899",
    inputs: 1,
    outputs: 1,
    icon: "FileCode",
  },
  [NodeType.COMPRESS]: {
    type: NodeType.COMPRESS,
    label: "Compress",
    description: "Compress and decompress data",
    category: "data",
    color: "#ec4899",
    inputs: 1,
    outputs: 1,
    icon: "Archive",
  },
  [NodeType.GOOGLE_SHEETS]: {
    type: NodeType.GOOGLE_SHEETS,
    label: "Google Sheets",
    description: "Read/write Google Sheets",
    category: "integration",
    color: "#6366f1",
    inputs: 1,
    outputs: 1,
    icon: "Table",
    credentialType: "GOOGLE",
  },
  [NodeType.GOOGLE_CALENDAR]: {
    type: NodeType.GOOGLE_CALENDAR,
    label: "Google Calendar",
    description: "Manage Google Calendar events",
    category: "integration",
    color: "#6366f1",
    inputs: 1,
    outputs: 1,
    icon: "CalendarDays",
    credentialType: "GOOGLE",
  },
  [NodeType.GOOGLE_DRIVE]: {
    type: NodeType.GOOGLE_DRIVE,
    label: "Google Drive",
    description: "Manage Google Drive files",
    category: "integration",
    color: "#6366f1",
    inputs: 1,
    outputs: 1,
    icon: "HardDrive",
    credentialType: "GOOGLE",
  },
  [NodeType.GMAIL]: {
    type: NodeType.GMAIL,
    label: "Gmail",
    description: "Send and read Gmail",
    category: "integration",
    color: "#6366f1",
    inputs: 1,
    outputs: 1,
    icon: "Mail",
    credentialType: "GOOGLE",
  },
  [NodeType.GRAPHQL]: {
    type: NodeType.GRAPHQL,
    label: "GraphQL",
    description: "Execute GraphQL queries",
    category: "integration",
    color: "#6366f1",
    inputs: 1,
    outputs: 1,
    icon: "Braces",
  },
  [NodeType.POSTGRESQL_QUERY]: {
    type: NodeType.POSTGRESQL_QUERY,
    label: "PostgreSQL",
    description: "Execute PostgreSQL queries",
    category: "integration",
    color: "#6366f1",
    inputs: 1,
    outputs: 1,
    icon: "Database",
    credentialType: "POSTGRES",
  },
  [NodeType.MYSQL_QUERY]: {
    type: NodeType.MYSQL_QUERY,
    label: "MySQL",
    description: "Execute MySQL queries",
    category: "integration",
    color: "#6366f1",
    inputs: 1,
    outputs: 1,
    icon: "Database",
    credentialType: "MYSQL",
  },
  [NodeType.AI_AGENT]: {
    type: NodeType.AI_AGENT,
    label: "AI Agent",
    description: "Context-aware AI agent",
    category: "ai",
    color: "#8b5cf6",
    inputs: 1,
    outputs: 1,
    icon: "Bot",
  },
  [NodeType.OLLAMA]: {
    type: NodeType.OLLAMA,
    label: "Ollama",
    description: "Local LLM via Ollama",
    category: "ai",
    color: "#8b5cf6",
    inputs: 1,
    outputs: 1,
    icon: "Cpu",
    credentialType: "OLLAMA",
  },
  [NodeType.TEXT_CLASSIFIER]: {
    type: NodeType.TEXT_CLASSIFIER,
    label: "Text Classifier",
    description: "Classify text into categories",
    category: "ai",
    color: "#8b5cf6",
    inputs: 1,
    outputs: 1,
    icon: "Tags",
  },
  [NodeType.SENTIMENT_ANALYSIS]: {
    type: NodeType.SENTIMENT_ANALYSIS,
    label: "Sentiment Analysis",
    description: "Analyze text sentiment",
    category: "ai",
    color: "#8b5cf6",
    inputs: 1,
    outputs: 1,
    icon: "Smile",
  },
  [NodeType.INFORMATION_EXTRACTOR]: {
    type: NodeType.INFORMATION_EXTRACTOR,
    label: "Info Extractor",
    description: "Extract structured info from text",
    category: "ai",
    color: "#8b5cf6",
    inputs: 1,
    outputs: 1,
    icon: "Search",
  },
  [NodeType.AI_TRANSFORM]: {
    type: NodeType.AI_TRANSFORM,
    label: "AI Transform",
    description: "Transform data using AI",
    category: "ai",
    color: "#8b5cf6",
    inputs: 1,
    outputs: 1,
    icon: "Wand",
  },
  [NodeType.SUMMARIZATION]: {
    type: NodeType.SUMMARIZATION,
    label: "Summarization",
    description: "Summarize text content",
    category: "ai",
    color: "#8b5cf6",
    inputs: 1,
    outputs: 1,
    icon: "AlignLeft",
  },
};

export function getNodeMetadata(type: string): NodeMetadata | undefined {
  return nodeMetadataMap[type];
}

export function getNodesByCategory(
  category: NodeMetadata["category"],
): NodeMetadata[] {
  return Object.values(nodeMetadataMap).filter((m) => m.category === category);
}

export function searchNodes(query: string): NodeMetadata[] {
  if (!query) return Object.values(nodeMetadataMap);
  const lower = query.toLowerCase();
  return Object.values(nodeMetadataMap).filter(
    (m) =>
      m.label.toLowerCase().includes(lower) ||
      m.description.toLowerCase().includes(lower) ||
      m.type.toLowerCase().includes(lower),
  );
}
